name: prerelease

on:
  release:
    types: [prereleased]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      STAGE: prerelease

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm ci
